dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += cl-som-imx8.dtb cl-som-imx8-4k.dtb 
dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += cl-som-imx8-lvds-dcss.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += cl-som-imx8-lvds-lcdif.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += cl-som-imx8-dual.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += cl-som-imx8-csi.dtb
				
always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
